//Nome: Guilherme Antunes R.A:2142589
public class Jan1 extends javax.swing.JFrame {
    
    private static Jan1 jan1Unico;
    
    private Jan1() {
        initComponents();
    }

    public static Jan1 getJan1(){
        if(jan1Unico == null){
            jan1Unico = new Jan1();
        }
        return jan1Unico;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtJan1 = new javax.swing.JLabel();
        btFecJan1 = new javax.swing.JButton();
        rtInstru = new javax.swing.JLabel();
        rtCreditos = new javax.swing.JLabel();
        barMnPrinc = new javax.swing.JMenuBar();
        mnPrinc = new javax.swing.JMenu();
        mnItCafe = new javax.swing.JMenuItem();
        mnItPao = new javax.swing.JMenuItem();
        mnItBolo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela1");

        rtJan1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        rtJan1.setForeground(new java.awt.Color(0, 0, 204));
        rtJan1.setText("Cardápio Cafeteria Coffe Code </>");

        btFecJan1.setText("Fechar Programa");
        btFecJan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecJan1ActionPerformed(evt);
            }
        });

        rtInstru.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rtInstru.setText("Cilque no menu principal no topo da janela para ter acesso aos cardápios.");

        rtCreditos.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        rtCreditos.setText("Desenvolvido por Guilherme Antunes");

        mnPrinc.setText("Principal");

        mnItCafe.setText("Cardápio Café");
        mnItCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItCafeActionPerformed(evt);
            }
        });
        mnPrinc.add(mnItCafe);

        mnItPao.setText("Cardápio Pão");
        mnItPao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItPaoActionPerformed(evt);
            }
        });
        mnPrinc.add(mnItPao);

        mnItBolo.setText("Cardápio Bolo");
        mnItBolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItBoloActionPerformed(evt);
            }
        });
        mnPrinc.add(mnItBolo);

        barMnPrinc.add(mnPrinc);

        setJMenuBar(barMnPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(rtInstru))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(300, Short.MAX_VALUE)
                        .addComponent(btFecJan1)))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rtJan1)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtCreditos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(rtJan1)
                .addGap(18, 18, 18)
                .addComponent(rtInstru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btFecJan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtCreditos)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecJan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecJan1ActionPerformed
        dispose();
    }//GEN-LAST:event_btFecJan1ActionPerformed

    private void mnItCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItCafeActionPerformed
        JanCafe.getJanCafe().setVisible(true);
    }//GEN-LAST:event_mnItCafeActionPerformed

    private void mnItBoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItBoloActionPerformed
        JanBolo.getJanBolo().setVisible(true);
    }//GEN-LAST:event_mnItBoloActionPerformed

    private void mnItPaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItPaoActionPerformed
        JanPao.getJanPao().setVisible(true);
    }//GEN-LAST:event_mnItPaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getJan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMnPrinc;
    private javax.swing.JButton btFecJan1;
    private javax.swing.JMenuItem mnItBolo;
    private javax.swing.JMenuItem mnItCafe;
    private javax.swing.JMenuItem mnItPao;
    private javax.swing.JMenu mnPrinc;
    private javax.swing.JLabel rtCreditos;
    private javax.swing.JLabel rtInstru;
    private javax.swing.JLabel rtJan1;
    // End of variables declaration//GEN-END:variables
}
