//Nome: Guilherme Antunes R.A:2142589
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class JanBolo extends javax.swing.JFrame {
    
    private GerItem gerItem = new GerItem();
    private Bolo bolo = new Bolo();
    
    private static JanBolo janBoloUnico;
    
    private JanBolo() {
        initComponents();
    }
    
    public static JanBolo getJanBolo(){
        if(janBoloUnico == null){
            janBoloUnico = new JanBolo();
        }
        return janBoloUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtJanBolo = new javax.swing.JLabel();
        rtIdBolo = new javax.swing.JLabel();
        rtNomeBolo = new javax.swing.JLabel();
        rtPrecoBolo = new javax.swing.JLabel();
        rtSaborBolo = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtSabor = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btVoltarMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCardapio = new javax.swing.JTable();
        rtRecheio = new javax.swing.JLabel();
        txtRecheio = new javax.swing.JTextField();
        rtCobertura = new javax.swing.JLabel();
        txtCobertura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtJanBolo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtJanBolo.setText("Cardápio Bolo:");

        rtIdBolo.setText("ID:");

        rtNomeBolo.setText("NOME:");

        rtPrecoBolo.setText("PREÇO:");

        rtSaborBolo.setText("SABOR:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaborActionPerformed(evt);
            }
        });

        btAdd.setText("Adicionar Bolo");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDel.setText("Deletar Bolo");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btVoltarMenu.setText("Voltar para o menu");
        btVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarMenuActionPerformed(evt);
            }
        });

        tabCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "PREÇO", "SABOR", "RECHEIO", "COBERTURA"
            }
        ));
        jScrollPane1.setViewportView(tabCardapio);

        rtRecheio.setText("RECHEIO:");

        txtRecheio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecheioActionPerformed(evt);
            }
        });

        rtCobertura.setText("COBERTURA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtIdBolo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtPrecoBolo)
                            .addComponent(rtSaborBolo)
                            .addComponent(rtNomeBolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rtRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPreco)
                            .addComponent(txtNome)
                            .addComponent(txtId)
                            .addComponent(txtSabor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtRecheio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtCobertura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAdd)
                            .addComponent(btDel)
                            .addComponent(btVoltarMenu)
                            .addComponent(rtCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtJanBolo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtJanBolo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtIdBolo)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtNomeBolo)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtPrecoBolo)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtSaborBolo)
                            .addComponent(txtSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtRecheio)
                            .addComponent(txtRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtCobertura)
                            .addComponent(txtCobertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btVoltarMenu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        deletar();
        listarTabela();
    }//GEN-LAST:event_btDelActionPerformed

    private void btVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarMenuActionPerformed
        Jan1.getJan1().setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarMenuActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        adicionar();
        listarTabela();
        limpar();
    }//GEN-LAST:event_btAddActionPerformed

    private void txtRecheioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecheioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecheioActionPerformed

    private void txtSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaborActionPerformed

    public void listarTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) tabCardapio.getModel();
        modelo.setRowCount(0);
        int posLin = 0;
        
        for(Bolo bolo1 : gerItem.getBdBolo()){
            modelo.insertRow(posLin, new Object[]{bolo1.getId(),bolo1.getNome(),bolo1.getPreco(),bolo1.getSabor(),bolo1.getRecheio(),bolo1.getCobertura()});
            posLin++;
        }
    }
    
    public void adicionar(){
        bolo = new Bolo();
        bolo.setId(Integer.parseInt(txtId.getText()));
        bolo.setNome(txtNome.getText());
        bolo.setPreco(Float.parseFloat(txtPreco.getText()));
        bolo.setSabor(txtSabor.getText());
        bolo.setRecheio(txtRecheio.getText());
        bolo.setCobertura(txtCobertura.getText());
        bolo = gerItem.setBdBolo(bolo);
        
        if(bolo == null){
            JOptionPane.showMessageDialog(null, "Já existe um bolo com esse ID!", "Erro ao Adicionar", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Bolo Adicionado com sucesso!", "Adicionado com Sucesso", JOptionPane.OK_OPTION);
        }
    }
    
    public void deletar(){
        bolo = new Bolo();
        bolo.setId(Integer.parseInt(txtId.getText()));
        bolo = gerItem.delBolo(bolo);
        
        if(bolo != null){
            JOptionPane.showMessageDialog(null, "Bolo deletado com sucesso!", "Deletar Bolo", JOptionPane.OK_OPTION);
            limpar();
        }else{
            JOptionPane.showMessageDialog(null, "Não existe nenhum bolo com esse ID: "+txtId.getText(), "Erro ao deletar Pão", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }
    
    public void limpar(){
        txtId.setText("");
        txtNome.setText("");
        txtPreco.setText("");
        txtSabor.setText("");
        txtRecheio.setText("");
        txtCobertura.setText("");
        txtId.requestFocus();
    }
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getJanBolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btVoltarMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCobertura;
    private javax.swing.JLabel rtIdBolo;
    private javax.swing.JLabel rtJanBolo;
    private javax.swing.JLabel rtNomeBolo;
    private javax.swing.JLabel rtPrecoBolo;
    private javax.swing.JLabel rtRecheio;
    private javax.swing.JLabel rtSaborBolo;
    private javax.swing.JTable tabCardapio;
    private javax.swing.JTextField txtCobertura;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtRecheio;
    private javax.swing.JTextField txtSabor;
    // End of variables declaration//GEN-END:variables
}
